### ISSUE TITLE
Environment variables for hlint

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#147]
hlint was failing to execute because... long story short, on my system `stack exec` needs to be run with the `NIX_PATH` and `NIXPKGS_CONFIG` environment variables set correctly. I have them set as path variables in IntelliJ, but they're not getting set in the environment when hlint is run.

**Comment by rikvdkleij** [comment]
hlint is run with `stack exec -- hlint`, so it's run in stack environment. I would assume that those: https://docs.haskellstack.org/en/stable/nix_integration/#configuration would be available.

The external executables are already run in `CONSOLE` environment.

Otherwise I need to extend the Haskell Settings panel with those env nix vars and always pass them when external tools are executed.

**Comment by chris-martin** [comment]
Ah, you're right. I can set the nix path in my global Stack config, so that's fine. As for NIXPKGS_CONFIG, I suppose it isn't very important.
