### ISSUE TITLE
Typing is slow when hlint is enabled

### ISSUE THREAD

**Issue by chris-martin** [rikvdkleij/intellij-haskell#148]
I had this problem before, and it was solved by upgrading to hlint 1.9.40 (`stack build hlint-1.9.40 haskell-src-exts-1.18.2`).

But after I upgraded my project dependencies to LTS 8.0, it's back to being slow again, and I've had to disable the hlint inspection.

**Comment by rikvdkleij** [comment]
It's hard problem to keep IDE responsive. It's because of the external tools/dependencies and also because IntelliJ platform is more or less a blackbox. I'm aware of this problem and are trying to solve this.

I'm already made some changes to improve the general responsiveness. I'm still testing those. If you want I can upload this new version so you can give it a try. 

I upgraded a project to LTS 8.0 (hlint 1.9.41) and I do not notice this problem with my latest local version.

**Comment by chris-martin** [comment]
After upgrading to IntelliJ 2017, it's back to being slow all the time, even when hlint is disabled.

**Comment by rikvdkleij** [comment]
Can you try to boot IntelliJ with the bundled OpenJDK?

You can do it by `Ctrl+Shift+A` and then type `switch IDE Boot JDK`

**Comment by rikvdkleij** [comment]
Okay, I found the cause. I will solve it in next beta.

**Comment by chris-martin** [comment]
The JetBrains JDK isn't packaged for NixOS yet. I hope to get around to addressing that at some point. https://github.com/NixOS/nixpkgs/issues/23115

**Comment by rikvdkleij** [comment]
Should be fixed in beta7.

**Comment by chris-martin** [comment]
It is, thanks as usual. Hlint still a little sluggish, but working great with it disabled.

**Comment by rikvdkleij** [comment]
Can you try it again in beta8?

**Comment by chris-martin** [comment]
Fantastic! :smiley:
