### ISSUE TITLE
Automatically build hindent and stylish-haskell

### ISSUE THREAD

**Issue by zjhmale** [rikvdkleij/intellij-haskell#154]
@rikvdkleij Currently, hindent and stylish-haskell are all in the LTS now, so maybe we can automatically build them for users instead of asking them to install the tools manually.

**Comment by zjhmale** [comment]
This should be closed due to the discussion here #94.

**Comment by rikvdkleij** [comment]
As far as I know, they do not depend on GHC API.  Advantage of asking is that they do not have to be build for each project separately. So project is faster ready to be used.

Some brainstorming:
Other solution would be to build them automatically and use them throughout the projects. In that solution we have to build them by a fixed Stackage LTS version. I think we can use `stack install` and option `--no-copy-bins`, so we can put them for example in `.ideaHaskellBin`.  Problem is which fixed Stackage LTS version to use? You do not want to download GHC only for building these tools.

Otherwise we have to build them automatically for each major Stackage LTS version. So you get for example `.ideaHaskellBin/LTS8` and `.ideaHaskellBin/LTS7`, if user has projects which uses only those 2 major Stackage LTS versions.

**Comment by rikvdkleij** [comment]
Hmm, we can use same solution for the other tools to prevent that tool is build again for same Stackage major LTS version in other project :smile:

**Comment by zjhmale** [comment]
Sorry, I can not see the connection, if we use `--no-copy-bins`, how can we get the executables and put them in `.ideaHaskellBin` for example?
>I think we can use stack install and option --no-copy-bins, so we can put them for example in .ideaHaskellBin

**Comment by rikvdkleij** [comment]
> I think we can use stack install and option --no-copy-bins, so we can put them for example in .ideaHaskellBin

Point is I do not want to "pollute" users his environment by overriding executables on his path. So idea was to build tool, move to IntelliJ known location and then use `stack exec --` with path to executable.

Taking a second look, we can also reuse binaries in `local-install-root`. Run `stack path` to see this path. Wait, maybe `stack` is already reusing already build binaries for LTS versions...... Something to investigate
