### ISSUE TITLE
Intention for adding type signature

### ISSUE THREAD

**Issue by solicode** [rikvdkleij/intellij-haskell#224]
I often find myself writing code without type annotations at first, but later wanting to add them for clarity/documentation for top level declarations. I think having an intention to do this rather than having to type them out would be nice.

It seems like it would be fairly simple to implement. Most of the code needed for this feature already exists I think. Probably just need a helper function to check whether a function is already annotated or not (unless this helper already exists?).

Actually, this doesn't necessarily need to only apply to top-level declarations. If you highlight something local, the intention could change `something` to `(something :: SomeType)`. Maybe it wouldn't see as much use though.

**Comment by rikvdkleij** [comment]
When you enable `-Wall` you already have the intention. But yes, it could also be added without help of the compiler warning. Especially for top level declarations.

>  If you highlight something local, the intention could change something to (something :: SomeType)

Yes, I also do not see need for that intention.

What would be nice is to create intention for generating type signature for binding inside where clause but that is difficult/tricky because parser is not clever enough.....

**Comment by solicode** [comment]
Ah, I didn't realize that appears with `-Wall`. That works for me. Thanks for letting me know.

So I guess this isn't much of a priority (at least for me). Having it possible without `-Wall` could still be nice though.

As for other situations where it can be used, I'll have to give it more thought. Too bad about the `where` thing though.

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
