### ISSUE TITLE
Add ability to turn off code inspections on a per-file or per-project basis

### ISSUE THREAD

**Issue by sjking** [rikvdkleij/intellij-haskell#234]
[White-listing and Blacklisting](https://github.com/commercialhaskell/intero#whitelistingblacklisting-projects) of projects is supported in [intero](https://github.com/commercialhaskell/intero).

Working on a large code base using multiple projects, we're running into IDE performance issues with code inspections on certain large files. These issues are causing the IDE to freeze for extended periods of time. This issue might be related to this issue #186.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

Haskell files are loaded by REPL with Intero in a background thread so that can not be the reason that IDE is unresponsive. It could be caused by Hlint inspection. You can see if Hlint is causing this problem by disabling Hlint inspection. 

To solve this issue I have to reproduce it. Can you give me a link to (example) project?

Issue #186 is about something else. That issue is about generating Haddock documentation.

**Comment by sjking** [comment]
Thanks for the quick response.

I tried to disabled HLint but there is still a problem with the IDE becoming unresponsive. This happens when I edit some source files. When the IDE is unresponsive I can see that there is a single `intero` process that is running at 100% CPU usage from the output of `top`. I'm not sure yet how to reproduce, but will let you know when I have a link to an example.

**Comment by rikvdkleij** [comment]
Forgot to mention that when IDE freezes it dumps thread logs. Can you send those to me?

The plugin depends for many features on the REPL which has loaded Intero. So when Intero goes crazy it does has it's effect...

**Comment by rikvdkleij** [comment]
> I'm not sure yet how to reproduce, but will let you know when I have a link to an example.

Thanks 👍

**Comment by rikvdkleij** [comment]
Please reopen when it's still an issue.
