### ISSUE TITLE
Donations: where to send them?

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#243]
Subj.

**Comment by rikvdkleij** [comment]
Thanks but I do need donations. I rather prefer contributions in any form whatsoever 😄

**Comment by csi-adziahel** [comment]
Nah, I'd rather pay than learn Scala

**Comment by rikvdkleij** [comment]
Well, you can also contribute with e.g. documentation and website.

**Comment by pjan** [comment]
Maybe for a fund to sponsor an intern to work on the features/issues? Similar as to what Ensime (Scala) has been doing?

**Comment by ice1000** [comment]
This plugin really needs contribution. I've already seen a lot of places where we can improve.

My time is limited, and I'm having final exams this week (I'm an undergrats freshman). I have a lot of other works to do as well (like my own plugins, my intern, my programming language), so I can't implement everything I want myself.

I'll try to throw my prospects in the issues (instead of just thinking myself).
What I want to say here is, it's not hard to `[use Scala|develop plugin]`, especiallywhen there're 3 Haskell plugins you can learn from. You guys are highly encouraged to contribution (as Rik mentioned), so please try!

**Comment by rikvdkleij** [comment]
> I hate the parser of intellij-haskell, 

Well, it's approximation works pretty well :wink:

**Comment by rikvdkleij** [comment]
Because I'm still maintaining the plugin and it takes me a lot of free time I have decided to accept donations :smile: The Donate button is here https://github.com/rikvdkleij/intellij-haskell
