### ISSUE TITLE
How do you switch build targets?

### ISSUE THREAD

**Issue by emhoracek** [rikvdkleij/intellij-haskell#274]
I have a project with a library and test suite. Things work pretty well in the library modules. But when I'm working on the test suite, it doesn't seem to be watching my changes for errors. If I attempt to compile the test suite, the editor then highlights the errors.

In Emacs, I'd switch targets explicitly with `intero-targets` when I was going to work on tests (which was pretty annoying but it worked).

Happy to give more info if needed.

**Comment by rikvdkleij** [comment]
It should switch automatically but I have to admit that the solution is not robust. See also #273 . 

It should only watch for changes in library files and trigger rebuild. So that when you navigate from library code to test code, the library gets rebuild and when it's finished it should restart the REPL of the test sources.

**Comment by emhoracek** [comment]
Oh, I saw that issue but didn't realize it was the same thing! I'll go over there and add my thoughts. Thanks for the quick response!
