### ISSUE TITLE
IDE about String as JsString

### ISSUE THREAD

**Issue by ndmitchell** [rikvdkleij/intellij-haskell#287]
```
import (Foo)
```

Leads to an IDE error of:

```
Expected String as JsString, but got []
```

**Comment by rikvdkleij** [comment]
Should be fixed in the latest betas which are not officially released yet. You can try beta17 https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta17

I hope to release beta18 this weekend and if that one works correctly version 1.0 will be released. Doing more testing than before.

**Comment by ndmitchell** [comment]
Confirmed that seems to fix it - great!
