### ISSUE TITLE
Display "Starting project REPLs" task progress

### ISSUE THREAD

**Issue by develop7** [rikvdkleij/intellij-haskell#371]
Right now it is just spinning indefinitely until all REPLs are started. In a project of 15-something packages it takes minutes, waiting for which makes user hanging.

**Comment by rikvdkleij** [comment]
Well, it should not spin indefinitely but yes it can take some time if project contains 15 packages. Point is between starting 2 REPLs, 5 seconds have to be waited otherwise Stack will give an error.

I will change the solution and hopefully that will help and not raise another issue :smile: 

Final solution is to replace ghc/intero.

**Comment by develop7** [comment]
By "indefinitely" I meant there's no way to track its' progress.

**Comment by develop7** [comment]
Thanks, man, these should do!

**Comment by rikvdkleij** [comment]
Is this fixed?

**Comment by develop7** [comment]
Sorry, yeah, it did it. Thanks!
