### ISSUE TITLE
Live templates have a bad context

### ISSUE THREAD

**Issue by Sir4ur0n** [rikvdkleij/intellij-haskell#391]
There are a few default live templates (e.g. `data`, `datag`) which have an invalid context. They have `Haskell / Global definition` enabled but it never prompts the template:
![image](https://user-images.githubusercontent.com/1204125/52949485-afce3980-337c-11e9-8973-5a96c59c10df.png)

However by enabling `Other` it works:
![image](https://user-images.githubusercontent.com/1204125/52949501-be1c5580-337c-11e9-882b-bfa6bf2aaa98.png)
![image](https://user-images.githubusercontent.com/1204125/52949516-c5436380-337c-11e9-9c89-d60af2503081.png)
![image](https://user-images.githubusercontent.com/1204125/52949534-d3917f80-337c-11e9-9b42-55d99f4d46cb.png)

The default context should be fixed for all applicable live templates.

Also, it may be cool to rename `Other` to something more explicit?

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I never use this feature but will take a look.

**Comment by ice1000** [comment]
I made this. Sorry for the problem 😅

**Comment by ice1000** [comment]
You may try to fix this context detection code:

https://github.com/rikvdkleij/intellij-haskell/blob/c174113b0d27a3a053e88e9d5d6796aee0af46cc/src/main/scala/intellij/haskell/editor/HaskellLiveTemplate.scala#L25-L33

instead of just changing the context id in plugin.xml

Your change makes the context type above unused. Maybe delete it? I'm not satisfied with that context as well.
