### ISSUE TITLE
Focus stealing

### ISSUE THREAD

**Issue by mnn** [rikvdkleij/intellij-haskell#443]
When code is not valid, occasionally "Messages" dock opens/closes and often "Project" dock ends up having focus. In some instance this starts happenning every few keystrokes. Maybe related to #273? I even once ended up deleting one module, because I was writing, didn't notice focus got stolen and I hit <kbd>del</kbd> followed by <kbd>enter</kbd>. I am glad IDEA keeps history of deleted files...

I recorded video from beta48 (didn't notice new version is out), but I retested and it does same thing in beta49, only less frequently, because it seems changes to code aren't being reflected too often. In beta49 I started getting REPL 30 second timeout, with command was: ":show modules". Probably not related.

![idea_focus_stealing](https://user-images.githubusercontent.com/1975567/59868972-77725280-9392-11e9-8577-1633782f3884.gif)

Shown project was created by `File -> New -> Project...` in IDEA. I am pretty sure this behaviour occurs in every project (at least for me).

**Comment by rikvdkleij** [comment]
Thanks for reporting!

> In beta49 I started getting REPL 30 second timeout, with command was: ":show modules". Probably not related.

This issue is fixed in the recently released beta50 (issue was introduced by replacing intero with vanilla ghci).


About the focus stealing. When your Lib module has changes and you navigate to Main module (in exe target), the plugin will rebuild the library code (because of the changes) The exe code runs in different REPL than the library code. So to make the library changes visible in the exe REPL the lib code will be rebuild and when that is successfully the exe REPL will be restarted. In your case the lib does not build successfully and the errors will be displayed in the Messages window. That triggers for some reason that sometimes the focus moves away to the Project window. Do not know why, probably via the Messages window.

Do not know how to solve this properly. I can run the rebuild of the library code completely in the background but then maybe those errors are not clear anymore because you have moved to another module.

I think the most simple solution is to move the rebuild of the library code completely in the background and use the Haskell Problems View to keep overview of errors and warnings. What do you think? This would also mean the instructions in the README should emphasize the usage of the Haskell Problems View.

**Comment by mnn** [comment]
Oh, I didn't even know there is a Haskell Problems View :sweat_smile:. It sounds like a good idea. I agree it should be emphasized in README and maybe later consider coming up with some way how to present a user with that View naturally, e.g. by automatically opening it when IDEA is launched for a first time with plugin installed (or maybe after creating new Haskell project)?

I know this issue has a partial workaround - closing all those docks on left. I forgot to mention that it happened to me few times that a focus moved to Messages, but I don't know how to replicate that. :slightly_frowning_face:

**Comment by rikvdkleij** [comment]
Released beta51, https://github.com/rikvdkleij/intellij-haskell/releases/edit/v1.0.0-beta51

Also uploaded to Jetbrains plugin repo but it can take some time before they approve.

I'm curious how you experience beta51 :smile:

**Comment by rikvdkleij** [comment]
@mnn  Can this issue be closed?

**Comment by mnn** [comment]
Sorry, totally forgot about this ticket. Just tested in beta51 and it works flawlessly, good job. :slightly_smiling_face:
