### ISSUE TITLE
Haskell indentation behaving erratically

### ISSUE THREAD

**Issue by koflerdavid** [rikvdkleij/intellij-haskell#45]
Hello,

First of all I'd like to express my gratitude for the efforts you put into developing this plugin and maintaining it for the community :-)

I found an annoying problem with the indentation. Given I use record syntax for a datatype, when I add a new line, then the whole declaration keeps marching to the right. I found no way to stop this from happening within IntelliJ; even turning off Smart indent didn't work.
EDIT: Similar things happen with the `do` syntax.

I have attached a short video to illustrate what's happening. I had to put it into a ZIP file because I don't want to bother with Youtube for an 8 sec screencast.
[screencast.zip](https://github.com/rikvdkleij/intellij-haskell/files/478566/screencast.zip)

EDIT: If these details are not enough for debugging I can provide you with further information. If it is not possible to diagnose and fix, it would also be acceptable for me to be able to turn the feature off completely.

**Comment by koflerdavid** [comment]
It seems to be related to the save actions. When I turned off the "Reformat file" save action then the problem is gone.

**Comment by rikvdkleij** [comment]
Thanks for your kind words. Yes, it's a lot work to create and maintain Haskell plugin. Also because the evolving ecosystem.

I'm busy with rewrite of plugin which depends mainly on Stack and Intero. In this new version of plugin I removed the IntelliJ formatting support because I could not find solid solution. My plan is to integrate hindent for formatting support.

**Comment by rikvdkleij** [comment]
Version 1.0.0-beta3 supports formatting with Hindent and/of Stylish-haskell.
