### ISSUE TITLE
Add Intention actions

### ISSUE THREAD

**Issue by rikvdkleij** [rikvdkleij/intellij-haskell#57]
For example to add type signature to where binding or to add parens around expression.

**Comment by zjhmale** [comment]
@rikvdkleij

I just tried to  add type signature to where binding, but meet a few obstacles.

## What we already got

* Get type signature for a specific PsiElement, [findTypeInfoForElement](https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/external/component/StackReplsComponentsManager.scala#L90).

* A pretty neat way to add type signatures for declarations, [TypeSignatureIntentionAction](https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/annotator/HaskellAnnotator.scala#L247).

## What we are missing

* The element type of binding declaration itself and its parameters are all [HaskellTokenType.VAR_ID](https://github.com/rikvdkleij/intellij-haskell/blob/master/gen/intellij/haskell/psi/HaskellTypes.java#L181), so it's hard to determine whether current caret is focus on the binding declaration or just focus on a function parameter.

* Because the [where PsiElement](https://github.com/rikvdkleij/intellij-haskell/blob/master/gen/intellij/haskell/psi/HaskellTypes.java#L183) is isolated from its bindings, so it is hard to determine whether current caret is inside a where block or not.

* The binding and its type signature are both isolated in the Psi Structure, so it is also hard to check whether there is already a type signature for the where binding or not.

**Comment by rikvdkleij** [comment]
Solution is to improve the psi tree by changing haskell.bnf.

**Comment by zjhmale** [comment]
@rikvdkleij ok.
