### ISSUE TITLE
can't start project because Stack binary not in path

### ISSUE THREAD

**Issue by pro3s** [rikvdkleij/intellij-haskell#587]
after plugin update.  the message appears 
"can't start project because Stack binary no in the path"
project opened anyways and even run but there is yellow stripe on top with the same message
I've tried to play with PATH variable not luck 
tried to reinstall plugin the same 

env: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet
in my case stack binaries located in /usr/local/bin

**Comment by tomlanning** [comment]
Same message.  _macOS_ version 10.15.5, _Intellij IDEA_ 2020.1.3.  _Stack_ (version 2.3.1) installed via _brew_.  Directory "/usr/local/bin" is on _PATH_.  "/usr/local/bin/stack" is a link to another location maintained by _brew_.  Is the symbolic link causing the problem?

I closed and removed the project from _Intellij IDEA_, uninstalled the plugin via _Intellij IDEA_, blew away the plugin cache, uninstalled _haskell-stack_ via _brew_, reinstalled everything, opened the project and got the same message again.  Project builds, tests, and runs fine from the command line.  Also verified that the terminal window opened by _Intellij IDEA_ has "/usr/local/bin" on _PATH_.

**Comment by rikvdkleij** [comment]
Thanks for reporting!

I have tested the latest version on Ubuntu and macOS (brew) and the plugin could find `stack` on the PATH. Also `Stack` should not be an issue.

> Is the symbolic link causing the problem?

No, on my machine it's the same.

Are you sure the name of the stack binary is `stack`?
Does the binary has the executable flag?

**Comment by erdeszt** [comment]
I'm having the same issue macos `10.14.6` after updating the plugin. Intellij version `2020.1.3`, plugin version: `1.0.0-beta76`
My setup:
```
⇒ which stack
/usr/local/bin/stack
⇒ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/Users/erdeszt/bin:/Users/erdeszt/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/Users/erdeszt/bin:/Users/erdeszt/.local/bin
⇒ file $(which stack)
/usr/local/bin/stack: Mach-O 64-bit executable x86_64
⇒ la $(which stack)
-rwxr-xr-x  1 erdeszt  admin  33321088 Jun 11 08:31 /usr/local/bin/stack
```
The project works fine from cli.

**Comment by rikvdkleij** [comment]
Can you try https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta77 ?

**Comment by shaigeva** [comment]
Unfortunately, at least for me the fix did not work.
I'm having the same issue, both with beta76 and beta77 (Intellij ultimate 2020.1.3).

Another piece of information - I ran a dev instance (I’ve recently started developing a plugin myself), and when I installed intellij-haskell on the dev instance (2019.3 CE, I think) - it works with no issues. There might be differences between dev instances and standard intellij, of course, but I don’t know them.


Btw, for what it’s worth with my very limited knowledge, I had a look at the code and combined with the above, if I had to guess, the problem is one of two:
1. There’s an env var passed into the stack process called “PATH”, in which case the original path is completely overridden, hence stack not being on the path.
2. (more likely) isStackOnPath returns false because of an exception, probably due to an intellij platform version incompatibility.

I’d be happy to try another version. Maybe a diagnostic version with try-catch for each side-effect in the function + capture the result and a message box that prints all the collected info at the end / catch block?

**Comment by shaigeva** [comment]
Ok I have a workaround! (works for me, at least)
I ran intellij from cli and the plugin works.

`$ open -na "IntelliJ IDEA.app"`

**Comment by rikvdkleij** [comment]
@shaigeva Thanks for your feedback!!

Because it works for you when you start IntelliJ from the CLI, i would conclude that this issue happens when the GUI environment does not have the PATH env var.

1.) and 2.) are very unlikely

My conclusion is that the most simple solution is to add a global setting in the Haskell Settings which contains the location of the stack executable. So in case user notices that IntelliJ can't find the stack exe, it uses that as fallback.

**Comment by shaigeva** [comment]
Seems like that indeed, although there is some weirdness - I did check what PATH intellij had ("ps -p <PID> -wwwE") and it seems like whichever way I run intellij, the PATH does contain the directory with the stack executable.

Anyhow, would be happy to help with testing.

**Comment by tomlanning** [comment]
I also have the different behavior with beta77 as @shaigeva when run from the command line.  With either startup method the  _Project Structure_ panel shows _Project SDK_ listed as `<No SDK>` and _Haskell Tool Stack_ is displayed in red as `Haskell Tool Stack [Invalid]`.  The _Edit_ button for the _Project SDK_ is active, but nothing happens if I press it.

**Comment by rikvdkleij** [comment]
Does your `Path Variables` setting in Settings also contain a `PATH` variable?

**Comment by rikvdkleij** [comment]
@shaigeva 
> - I did check what PATH intellij had ("ps -p -wwwE") and it seems like whichever way I run intellij, the PATH does contain the directory with the stack executable.

Yes, that's weird. I checked again the (library) code which is used to check if stack is on PATH and it uses the console environment variables.

**Comment by tomlanning** [comment]
> Does your `Path Variables` setting in Settings also contain a `PATH` variable?

No.  I only have 1 variable, `MAVEN_REPOSITORY` no matter which way I start _Intellij IDEA_.

**Comment by joshuakfarrar** [comment]
> Can you try https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta77 ?

Having the same issue on Windows 10. Used this, no executables listed when attempting to add Stack to my Haskell run configuration.

**Comment by wiwiwa** [comment]
Same problem on MacOS 10.15.5 with IDEA 2020.1.3.

Works by manually install plugin version [1.0.0-beta75](https://plugins.jetbrains.com/plugin/8258-intellij-haskell/versions/stable/89588)

**Comment by Turmiht** [comment]
same issue in macos10.15 with IDEA2020.2 EAP, @shaigeva's workaround helps, it's still weird to me however

**Comment by rikvdkleij** [comment]
I have reverted the change which removed the Haskell SDK and made the plugin depend on stack from the PATH.

Just released:
https://github.com/rikvdkleij/intellij-haskell/releases/tag/v1.0.0-beta78

Sorry for the inconvenience.

In the next version I will create a setting which indicates to use stack from PATH instead of SDK.

**Comment by rikvdkleij** [comment]
Please reopen if still an issue.

**Comment by cata0309** [comment]
That happened to me because the Stack executable was not found, mine is in `/usr/bin/stack` but the extension looks into `/usr/local/bin/stack` so I created that directory and created a symbolic link using `sudo ln -s /usr/bin/stack /usr/local/bin/stack` and now it works without problems
