### ISSUE TITLE
Haskell parsing

### ISSUE THREAD

**Issue by clojj** [rikvdkleij/intellij-haskell#82]
No issue, just a question about parsing in general, and maybe about missing tests...

"Then I decided to use grammar and lexer definitions only for tokenizing and parsing Haskell code, and not for syntax checking the code. This is needed for syntax highlighting, all kinds of navigation and so on. Further Haskell language support is provided with the help of external tools."

Could you elaborate, what the currently implemented parser can't handle ?
Also, I can't find any tests for the parser. Some tests could clarify the scope of what is possible with the GrammarKit parser.
Is the GrammarKit feature of error recovery used/planned ?

Intero has a "check source" command. Is intero used here for parsing in any way ?

Please note that this is not a critique of this outstanding(!) plugin
I am just curious, what could be improved upon in the long run.... as my guess is that robust and efficient parsing can indeed be improved (?)

**Comment by zjhmale** [comment]
Yes, currently this project is lacking tests. @rikvdkleij maybe we should start to match up the testing part to some degree. 
>Also, I can't find any tests for the parser. Some tests could clarify the scope of what is possible with the GrammarKit parser.

Do you mean make the parsing part faster? I believe during the long run, mostly are intero commands are running there.
>I am just curious, what could be improved upon in the long run.... as my guess is that robust and efficient parsing can indeed be improved (?)

**Comment by clojj** [comment]
What I meant is this intero function:
https://github.com/commercialhaskell/intero/blob/master/src/InteractiveUI.hs#L1469

**Comment by zjhmale** [comment]
The `:check` command seems only for finding global and local names,

![image](https://cloud.githubusercontent.com/assets/6234553/21379763/4d3edcca-c78b-11e6-857e-51391fc93a58.png)

And I can not see any usage in the emacs-mode, so what exactly we can improve the parser using the `:check` command?

**Comment by rikvdkleij** [comment]
Yes, we definitely need tests for parsing. Also more tests in general. Complicated factor is that plugin relies heavily on external tools.

There is no clear definition what plugin's parser/bnf supports. I started with Haskell 2010 but that is much too limited. What I mean to say in Readme is that parser has to exact enough to integrate/support IntelliJ features and general enough to parse all GHC code. bnf is not expressive enough to support all GHC code, There is also no bnf definition for all valid GHC code. Only for Haskell 2010.

The plugin uses as much as possible Intero and Ghci functions to do his job. Because plugin itself does not "understand" Haskell code. Also basic usage search depends on these external tools.

**Comment by clojj** [comment]
@zjhmale 
Sorry, I was mistaken by 'check'
You are right, :load does the job, and I can see that it is already used by this plugin.

**Comment by zjhmale** [comment]
@clojj No worries 😄
